export const PLANS = [
  {
    key: "free",
    name: "Free",
    priceUSD: 0,
    priceINR: 0,
    period: null,
    minutes: 120,
    features: ["5 hooks per video", "3 Shorts per video", "Watermarked"],
    cta: "Start Free",
    highlighted: false,
  },
  {
    key: "lite",
    name: "Lite",
    priceUSD: 7,
    priceINR: 499,
    period: "mo",
    minutes: 100,
    minutesLabel: "100 watermark-free minutes",
    features: ["5 hooks per video", "3 Shorts per video", "100 watermark-free minutes", "Priority support"],
    cta: "Go Lite",
    highlighted: true,
  },
  {
    key: "pro",
    name: "Pro",
    priceUSD: 13,
    priceINR: 999,
    period: "mo",
    minutes: 500,
    minutesLabel: "500 watermark-free minutes",
    features: ["5 hooks per video", "Unlimited Shorts", "500 watermark-free minutes", "Priority support", "Early access"],
    cta: "Go Pro",
    highlighted: false,
  },
] as const;
